from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def build_incident_pdf(session, events, risk, verdict_text):
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=54,
        leftMargin=54,
        topMargin=54,
        bottomMargin=54,
        title="ProctorVision Incident Report",
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Heading1"],
        fontSize=18,
        spaceAfter=12,
        textColor=colors.HexColor("#1a2744"),
    )
    h2 = ParagraphStyle(
        "ReportH2",
        parent=styles["Heading2"],
        fontSize=12,
        spaceBefore=14,
        spaceAfter=6,
        textColor=colors.HexColor("#2563eb"),
    )
    body = styles["BodyText"]

    story = [
        Paragraph("ProctorVision Proctoring Incident Report", title_style),
        Paragraph(
            "ProctorVision · Official Administrative Evidence Document",
            ParagraphStyle("sub", parent=body, textColor=colors.grey, fontSize=9),
        ),
        Spacer(1, 0.2 * inch),
    ]

    meta = [
        ["Student", session.get("student_name", "—")],
        ["Exam", session.get("exam_title") or session.get("exam_id", "—")],
        ["Session ID", session.get("id", "—")],
        ["Submission ID", session.get("submission_id") or "—"],
        ["Joined", session.get("joined_at", "—")],
        ["Submitted", session.get("submitted_at") or "—"],
        [
            "Exam Score",
            f"{session.get('score', '—')}/{session.get('total', '—')} ({session.get('pct', '—')}%)",
        ],
        ["Suspicion Score", f"{risk.get('suspicion_score', 0)}%"],
        ["Risk Level", risk.get("risk_level", "low").title()],
        ["Total Events", str(risk.get("event_count", len(events)))],
    ]
    meta_table = Table(meta, colWidths=[1.6 * inch, 4.5 * inch])
    meta_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cbd5e1")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    story.append(meta_table)

    story.append(Paragraph("AI Verdict Summary", h2))
    story.append(Paragraph(verdict_text.replace("\n", "<br/>"), body))
    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("Event Log", h2))
    if not events:
        story.append(Paragraph("No suspicious events were recorded.", body))
    else:
        rows = [["Time", "Type", "Details", "Weight"]]
        for ev in events[:80]:
            rows.append(
                [
                    (ev.get("created_at") or "")[:19],
                    ev.get("event_type", ""),
                    (ev.get("details") or "")[:120],
                    str(ev.get("weight", 0)),
                ]
            )
        log_table = Table(rows, colWidths=[1.2 * inch, 1.1 * inch, 3.3 * inch, 0.5 * inch])
        log_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a2744")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cbd5e1")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
                ]
            )
        )
        story.append(log_table)

    story.append(Spacer(1, 0.25 * inch))
    story.append(
        Paragraph(
            "<i>Generated by ProctorVision Backend · Flask + SQLite + ReportLab</i>",
            ParagraphStyle("foot", parent=body, fontSize=8, textColor=colors.grey),
        )
    )

    doc.build(story)
    buffer.seek(0)
    return buffer
